projects:
  Codegen Project:
    schemaPath: schema.graphql
    includes:
      - lib/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: lib/api.ts
        docsFilePath: lib/graphql
        region: us-east-1
        apiId: null
        frontend: javascript
        framework: none
        maxDepth: 10
extensions:
  amplify:
    version: 3
